### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FuckTheWorld/chromedriver#1112]
```
Issue Description:
We wanted to carry out the run for our regression tests on Chrome browser 
hosted on the Linux platform (Red Hat Enterprise Linux Server release 7.0 
(Maipo)).

Running selenium tests using Chrome (version- 43.0.2357.81 (64-bit)) as browser 
on Linux are failing to spawn a browser.

Steps to reproduce:
1. Chrome rpm was downloaded form the below link. 
"https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm".

2. Following chromedriver used (2.14.313457): 
http://chromedriver.storage.googleapis.com/2.14/chromedriver_linux64.zip

3. After installing chrome, the attached script (ChromeTest.java) was ran and 
I'm receiving the following error.

Stack trace: 

Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on 
port 3039
Only local connections are allowed.
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown 
error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.8.13-35.3.1.el7uek.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.20 seconds
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:11:15'
System info: host: 'localhost.localdomain', ip: '<>', os.name: 'Linux', 
os.arch: 'amd64', os.version: '3.8.13-35.3.1.el7uek.x86_64', java.version: 
'1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
        at ChromeTest.main(ChromeTest.java:36)



Please write back to me if any further information is needed.
Attaching the chromedriver.log
```

Original issue reported on code.google.com by `abhib...@gmail.com` on 1 Jun 2015 at 10:32

**Comment by ghost** [comment]
The same problem, chromedriver 2.20. Chromedriver log:
"....[60,162][INFO]: RESPONSE InitSession unknown error: Chrome failed to start: exited abnormally"

**Comment by japel** [comment]
@kenksis me too, same chromedriver version trying to call it from with builder ("selenium-webdriver": "2.47.0")
did you find any solution?

**Comment by ghost** [comment]
Hi. Unfortunately, not yet found. While use windows. Sorry for my English. I use google-translate

> Среда, 16 декабря 2015, 4:55 -08:00 от Jan Viktor Apel notifications@github.com:
> 
> @kenksis me too, same chromedriver version trying to call it from with builder ("selenium-webdriver": "2.47.0")
> did you find any solution?
> —
> Reply to this email directly or  view it on GitHub .

## 

С уважением, Евгений Кравцов

**Comment by seaify** [comment]
same with u
