### ISSUE TITLE
ChromeDriver does not start if instance of Chrome is running

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FuckTheWorld/chromedriver#1123]
```
See http://goo.gl/ll2FvQ for common issues.

Issue Description:
ChromeDriver does not start if instance of Chrome is running. 

Steps to reproduce (if relevant, you MUST provide a simplified html page or
link to public site):

Chrome Version 43.0.2357.124 (64-bit)
ChromeDriver 2.15.322455

SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 
1 (Exit value: 1)
Exception in thread "main" 
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new 
session. Possible causes are invalid address of the remote server or browser 
start-up failure.
Build info: version: '2.46.0', revision: 
'61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'BlaineA-MBP10.local', ip: '10.11.203.253', os.name: 'Mac OS 
X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: driver.version: ChromeDriver
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:116)
    at HTMLScrubber.<init>(HTMLScrubber.java:28)
    at Main.main(Main.java:9)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver 
server to start.
Build info: version: '2.46.0', revision: 
'61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'BlaineA-MBP10.local', ip: '10.11.203.253', os.name: 'Mac OS 
X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: driver.version: ChromeDriver
    at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:170)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:63)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
    ... 8 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out 
waiting for [http://localhost:16451/status] to be available after 20007 ms
    at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:104)
    at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:167)
    ... 10 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: 
java.util.concurrent.TimeoutException
    at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
    at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:79)
    ... 11 more
Caused by: java.util.concurrent.TimeoutException
    at java.util.concurrent.FutureTask.get(FutureTask.java:205)
    at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
    ... 12 more



-----Other helpful tips:
Attach your chromedriver log with verbose logging enabled (see
http://goo.gl/5Sx8mC for how to do this).

```

Original issue reported on code.google.com by `Blaineht...@gmail.com` on 10 Jun 2015 at 8:28

**Comment by Galileo1** [comment]
Did we had any break through for this issue? I see I was reported long time back but I am stuck with the same problem now. Any help is appreciated.
