### ISSUE TITLE
Get a "WebDriverException: disconnected: unable to receive message from renderer" error when switching browser windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FuckTheWorld/chromedriver#401]
```
What steps will reproduce the problem?
It's an internal application where I am testing the following scenario:
1. Once a file is uploaded successfully, the GUI page opens a new window (to 
display file information).
2. I switch on the new window--->click on OK to close this window.
3. Switch back to the previous parent window.
4. Before I can switch back to parent window, both the browser windows close 
(where only the new one should, after "OK" is clicked).

The exception that I get is:

org.openqa.selenium.WebDriverException: disconnected: unable to receive message 
from renderer
  (Session info: chrome=27.0.1453.116)
  (Driver info: chromedriver=0.7,platform=Windows NT 5.1 SP2 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 125 milliseconds
System info: os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', 
java.version: '1.7.0_17'
Session ID: 1fc5d8379d21099628679450b0b185e9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, 
browserName=chrome, rotatable=false, driverVersion=0.7, 
locationContextEnabled=true, version=27.0.1453.116, cssSelectorsEnabled=true, 
databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=false, 
webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, 
takesScreenshot=true}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
    at com.axway.webliv.utilities.tools.Tools$2.apply(Tools.java:201)
    at com.axway.webliv.utilities.tools.Tools$2.apply(Tools.java:1)
    at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)


What version of the product are you using? On what operating system?
ChromeDriver = 0.7
Chrome = 27.0.1453.116
OS = Windows XP

Please attach chromedriver.log to your bug report if possible.

```

Original issue reported on code.google.com by `natasha...@gmail.com` on 24 Jun 2013 at 11:41

Attachments:
- [chromedriver.log](https://storage.googleapis.com/google-code-attachments/chromedriver/issue-401/comment-0/chromedriver.log)

**Comment by Nandhis** [comment]
In Stackoverflow someone mentioned below code will resolve this issue.. I never  tested for myself.

System.setProperty("webdriver.chrome.driver","E:\\selenium\\chromedriver_2.41\\chromedriver.exe");
ChromeOptions options = new ChromeOptions();
options.setPageLoadStrategy(PageLoadStrategy.NONE);
driver = new ChromeDriver(options);
