### ISSUE TITLE
Clicking div with SVG image causes "cannot read property 'length' of undefined" error.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FuckTheWorld/chromedriver#427]
```
Before filing an issue, please read the page at
http://code.google.com/p/selenium/wiki/SeleniumHelp This contains lot of
information about how best to get help, and tells you what we need to know.

Still here? We know that bugs are frustrating and annoying things. We also
know that you've probably spent ages trying to figure out what's wrong. The
more information you give us now, the more likely it is that we'll be able
to help.

What steps will reproduce the problem?
1. open a popup div with class '.protractor .measurement-tool-image' that 
contains an SVG
2. try to click on geb object targeting '.protractor' with webdriver

What is the expected output? What do you see instead?

test fails immediately on click event

Selenium version: 2.29.1
OS: Mac OS X 10.6.8
Browser: Chrome
Browser version: 27.0.1453.116
Using Geb 0.7.2 with Spock

Please provide any additional information below. A sample reduced test
case, or a public URL that demonstrates the problem will intrigue our merry
band of Open Source developers far more than nothing at all: they'll be far
more likely to look at your problem if you make it easy for them!

// traceback

|Running 9 spock tests... 1 of 9
Failure:  |
Reduced Test Case(com.drc.test.RulerProtractorSpec)
 |
org.openqa.selenium.WebDriverException: isElementClickable execution failed;
 Cannot read property 'length' of undefined (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 67 milliseconds
Build info: version: '2.23.1', revision: 'unknown', time: '2012-06-08 12:33:29'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.6.8', 
java.version: '1.6.0_51'
Driver info: driver.version: RemoteWebDriver
Session ID: 6d6e28b8a9ac1d2c1e243e12cadf5b50
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:188)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:458)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:244)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
    at geb.navigator.NonEmptyNavigator.click(NonEmptyNavigator.groovy:297)
    at geb.content.TemplateDerivedPageContent.click(TemplateDerivedPageContent.groovy:105)
    at com.drc.test.RulerProtractorSpec.Reduced Test Case(RulerProtractorSpec.groovy:149)

//test 

    @IgnoreRest
    def "Reduced Test Case"() {
        given: "protractor is displayed"
        assert at(ItemPage)
        gotoItem(3)
        rulerProtractor.activateTool("protractor")
        assert rulerProtractor.protractor.displayed // this succeeds

        when: "protractor is clicked"
        rulerProtractor.protractor.click()

        then: "we don't really care"
        true
    }

// inside the rulerProtractor module:

    ruler(required: false) { $(".ruler .measurement-tool-image") }
    protractor(required: false) { $(".protractor .measurement-tool-image") }
```

Original issue reported on code.google.com by `jsz...@compcc.com` on 19 Jul 2013 at 2:48

**Comment by osmolyar** [comment]
Any updates on this?  Still seeing issue #1154 (as referenced above in w3c/webdriver#1266)

**Comment by osmolyar** [comment]
Additionally, it doesn't seem like it should be classified under 'chromedriver' but under webdriver (or webdriverio) as firefox also has an issue correctly clicking on elements inside the svg (the error is instead ```TypeError: container.frame is undefined```

reproducible example:
[svg.zip](https://github.com/FuckTheWorld/chromedriver/files/3248135/svg.zip)

And in IE, the error is "no frame found" (and in fact there isn't an <embed> element outside the svg in this case.)
